### PR TITLE
Added workaround for bit operaitions in incomplete environments 

### PR DESCRIPTION
**Pull request by AmsTaFFix**
Added workaround to add necessary functions. It will be helpful in environments, where not all necessary bit functions exists

### CODE REVIEW

**Comment by AmsTaFFix** [comment]
@somesocks

**Comment by greatwolf** [comment]
Which version of Lua/LuaJIT is this workaround for?

**Comment by AmsTaFFix** [comment]
> Which version of Lua/LuaJIT is this workaround for?

World of Warcraft LUA implementation

**Comment by AmsTaFFix** [comment]
@greatwolf does this PR suitable to merge, or I just should delete it?

**Comment by greatwolf** [comment]
It's up to @somesocks, I'm kind of neutral on it. I'm still wondering why WoW is using such an old version of Lua that doesn't have native bitwise operations in it.

**Review by somesocks — APPROVED** [review]

**Comment by somesocks** [comment]
I think my perspective is compatibility shims are small, so the cost-to-benefit ratio is high. :+1: from me.

**Pull request merged**
